### PR TITLE
Update product pages.

### PR DESCRIPTION
**Pull request by dfullaway**
Add product images. (Sparta and my Career images will need to be replaced with high quality images). Remove old navigation component. Remove reference to ViaSat. Metric cards will be off until the metric card PR is merged.

### CODE REVIEW

**Comment by wcrum** [comment]
Arent hose supposed to be GIFs?

**Comment by dfullaway** [comment]
@wcrum I only have access to the Figma page, and all the images there are PNGs. If someone has access to the original gifs, those should replace the PNGs I could pull.

**Comment by wcrum** [comment]
@dfullaway yea I will upload all of the content soon.

**Comment by wcrum** [comment]
@dfullaway please review recent changes. Mobile layout and for images that done have the secondary behind image might be useful to adjust padding.

**Review by wcrum — APPROVED** [review]
lgtm

**Pull request merged**
